spring:
  application:
    name: downloader
  cloud:
    config:
      enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/